apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: cagardap/ambulance-ufe
  newName: cagardap/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20231211.1419 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.2 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
